src/main/java/dto/ClientDto.java
package dto;

import java.util.ArrayList;

import javax.xml.bind.annotation.XmlRootElement;

import database.Repair;

@XmlRootElement
public class ClientDto extends ClientSummaryDto {
private ArrayList<Repair> repairs;

	public ArrayList<Repair> getRepairs() {
		return (ArrayList<Repair>) repairs;
	}

	public void setRepairs(ArrayList<Repair> indents) {
		this.repairs = repairs;
	}



}

src/main/java/dto/ClientSummaryDto.java
package dto;

public class ClientSummaryDto {

	private String name;
	private String address;
	private String city;
	private int phonenumber;
	
	public ClientSummaryDto(String name, String address, String city,
			int phonenumber) {
		super();
		this.name = name;
		this.address = address;
		this.city = city;
		this.phonenumber = phonenumber;
	}
	public ClientSummaryDto() {
		// TODO Auto-generated constructor stub
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public int getPhonenumber() {
		return phonenumber;
	}
	public void setPhonenumber(int phonenumber) {
		this.phonenumber = phonenumber;
	}

}

src/main/java/dto/EmployeeDto.java
package dto;


import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public class EmployeeDto extends EmployeeSummaryDto{

}

src/main/java/dto/EmployeeSummaryDto.java
package dto;


import database.Repair;

public class EmployeeSummaryDto {

	private String name;
	private String surname;
	private int dob;
	private int salary;
	private int phonenumber;
	
	public EmployeeSummaryDto(String name, String surname, int dob, int salary,
			int phonenumber) {
		super();
		this.name = name;
		this.surname = surname;
		this.dob = dob;
		this.salary = salary;
		this.phonenumber = phonenumber;
	}
	public EmployeeSummaryDto() {
		// TODO Auto-generated constructor stub
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSurname() {
		return surname;
	}
	public void setSurname(String surname) {
		this.surname = surname;
	}
	public int getDob() {
		return dob;
	}
	public void setDob(int dob) {
		this.dob = dob;
	}
	public int getSalary() {
		return salary;
	}
	public void setSalary(int salary) {
		this.salary = salary;
	}
	public int getPhonenumber() {
		return phonenumber;
	}
	public void setPhonenumber(int phonenumber) {
		this.phonenumber = phonenumber;
	}
	
}

src/main/java/dto/MotobikeDto.java
package dto;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class MotobikeDto extends MotobikeSummaryDto {

	//public MotobikeDto(){}
		
	
	public MotobikeDto(String licenseplate, String brand, String type, int enginecapacity,
			int timesunderrepair) {
		super(licenseplate, brand, type, enginecapacity, timesunderrepair);
		// TODO Auto-generated constructor stub
	}

	public MotobikeDto() {
		// TODO Auto-generated constructor stub
	}
	

}

src/main/java/dto/MotobikeSummaryDto.java
package dto;

public class MotobikeSummaryDto {

	private String licenseplate;
	private String brand;
	private String type;
	private int enginecapacity;
	private int timesunderrepair;
	
		public MotobikeSummaryDto(String licenseplate, String brand, String type,
			int enginecapacity, int timesunderrepair) {
		super();
		this.licenseplate = licenseplate;
		this.brand = brand;
		this.type = type;
		this.enginecapacity = enginecapacity;
		this.timesunderrepair = timesunderrepair;
	}
	public MotobikeSummaryDto() {
			// TODO Auto-generated constructor stub
		}
	public String getLicenseplate() {
		return licenseplate;
	}
	public void setLicenseplate(String licenseplate) {
		this.licenseplate = licenseplate;
	}
	public String getBrand() {
		return brand;
	}
	public void setBrand(String brand) {
		this.brand = brand;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public int getEnginecapacity() {
		return enginecapacity;
	}
	public void setEnginecapacity(int enginecapacity) {
		this.enginecapacity = enginecapacity;
	}
	public int getTimesunderrepair() {
		return timesunderrepair;
	}
	public void setTimesunderrepair(int timesunderrepair) {
		this.timesunderrepair = timesunderrepair;
	}	
	
	
}



src/main/java/dto/RepairDto.java
package dto;

import javax.xml.bind.annotation.XmlRootElement;

public class RepairDto extends RepairSummaryDto{

	private int ClientId;
	private int MotobikeId;
	private int WorkplaceId;
	public int getClientId() {
		return ClientId;
	}
	public void setClientId(int clientId) {
		ClientId = clientId;
	}
	public int getMotobikeId() {
		return MotobikeId;
	}
	public void setMotobikeId(int motobikeId) {
		MotobikeId = motobikeId;
	}
	public int getWorkplaceId() {
		return WorkplaceId;
	}
	public void setWorkplaceId(int workplaceId) {
		WorkplaceId = workplaceId;
	}
	
}

src/main/java/dto/RepairSummaryDto.java
package dto;

public class RepairSummaryDto {
	
	private int id;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

}

src/main/java/bins/RepairBean.java
package bins;
import java.io.Serializable;

import javax.enterprise.context.ApplicationScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;

import database.Repair;
import repositories.RepairRepository;
import service.MockUnitOfWork;

@ApplicationScoped
@Named
public class RepairBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Repair repair;

	private ListDataModel<Repair> repairs = new ListDataModel<Repair>();

	@Inject
	private MockUnitOfWork< Repair> mockUnitOfWork;

	private RepairRepository rm = new RepairRepository(mockUnitOfWork);

	public Repair getRepair() {
		return repair;
	}

	public void setRepair(Repair repair) {
		this.repair = repair;
	}

	public ListDataModel<Repair> getAllRepairs() {
		repairs.setWrappedData(rm.getAll());
		return repairs;
	}

	// Actions
	public String addRepair() {
		rm.persistAdd(repair);
		return "showRepairs";
		//return null;
	}

	public String deleteRepair() {
		Repair personToDelete = repairs.getRowData();
		rm.persistDelete(personToDelete);
		return null;
	}}

src/main/webapp/addRepair.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tpl/default.xhtml">
	<ui:define name="content">
		<h:form id="personform">
			<h:panelGrid columns="3">

				<h:outputText value="clientId" />
				<h:inputText id="clientId" value="#{repairBean.repair.clientId}" />
<br></br>
				<h:outputText value="motobikeId" />
				<h:inputText id="motobikeId" value="#{repairBean.repair.motobikeId}" />
<br></br>
				<h:outputText value="workplaceId" />
				<h:inputText id="workplaceId" value="#{repairBean.repair.workplaceId}" />
			</h:panelGrid>

			<h:commandButton value="ADD"
				action="#{repairBean.addRepair}" />
				
			<h:panelGrid>
				<h:messages showDetail="#{true}" showSummary="#{false}" />
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/addValidation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tpl/default.xhtml">
	<ui:define name="content">

		<h:form id="personForm">
            <f:event type="postValidate" listener="#{personBean.validatePinDob}" />
            
			<h:panelGrid columns="3">

				<h:outputText value="#{msg.personFirstNameLabel}" />
				<h:inputText id="firstName" value="#{personBean.person.firstName}" required="#{true}"/>

				<h:outputText value="#{msg.personPinLabel}" />
				<h:inputText id="pin" value="#{personBean.person.pin}"
					validator="#{personBean.uniquePin}" required="#{true}">
					<f:validator validatorId="pinValidator" />
				</h:inputText>

				<h:outputText value="#{msg.personDobLabel}" />
				<h:inputText id="dob" value="#{personBean.person.dateOfBirth}">
				  <f:convertDateTime type="date" pattern="dd.MM.yyyy" />
				</h:inputText>

				<h:outputText value="#{msg.personZipCodeLabel}" />
				<h:inputText id="zipCode" value="#{personBean.person.zipCode}" />

				<h:outputText value="#{msg.personWeightLabel}" />
				<h:inputText id="weight" value="#{personBean.person.weight}">
					<f:validateDoubleRange minimum="20.5" maximum="150.5" />
				</h:inputText>
			</h:panelGrid>
			
			<h:commandButton value="#{msg.personFormOKButton}"
				action="#{personBean.addPerson}" />


			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>
		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tpl/default.xhtml">
	<ui:define name="content">
<center>Damian Ciesielski s10363 - JAZ PROJEKT</center>
	</ui:define>
</ui:composition>

src/main/webapp/showRepair.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/tpl/default.xhtml">
	
	<ui:define name="content">
	
    <h:form>
    
     <h:dataTable value="#{repairBean.allRepairs}" var="item">
      <f:facet name="header">#{msg.repairAllLabel}</f:facet>
      
      <h:column>
        <f:facet name="header">#{msg.repairClientIdLabel}</f:facet>
        #{item.clientId}
      </h:column>
      
        <h:column>
        <f:facet name="header">#{msg.repairClientIdLabel}</f:facet>
        #{item.clientId}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.repairWorkplaceIdLabel}</f:facet>
        #{item.workplaceId}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.action}</f:facet>
        <h:commandButton value="DELETE REPAIR" action="#{repairBean.deleteRepair}"></h:commandButton>
      </h:column>
      
     </h:dataTable>
    </h:form>
      
	</ui:define>
	
</ui:composition>

src/main/webapp/tpl/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><ui:insert name="windowTitle">#{msg.mainWindowTitle}</ui:insert>
	</title>
</h:head>
<h:body>
  <h:outputStylesheet library="css" name="default.css" target="body" />
	<div class="heading">
	  <ui:insert name="heading">
       #{msg.mainHeading}
     </ui:insert>
    </div>
	<div class="menuAndContent">
	 <div class="menu">
	    <ui:insert name="menu">
         <ui:include src="/views/main/menu.xhtml" />
       </ui:insert>
      </div>
	  <div class="content">
	     <ui:insert name="content" />
       </div>
	</div>
</h:body>
</html>

src/main/webapp/views/main/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
  <div>
	<h:form>
	  <ul>
		<li>
		   <h:commandButton value="INDEX" action="index?faces-redirect=true"></h:commandButton>
		</li>
		<li>
		 <h:commandButton value="ADD REPAIR" action="addRepair?faces-redirect=true"></h:commandButton>
	</li>
		<li>
		 <h:commandButton value="SHOW REPAIR" action="showRepair?faces-redirect=true"></h:commandButton>
		</li>
	</ul>
   </h:form>
  </div>
</ui:composition>